// <auto-generated />
namespace TestParser.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Parserv11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Parserv11));
        
        string IMigrationMetadata.Id
        {
            get { return "202111101610301_Parserv1.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
